### ISSUE TITLE
Gradlew Eclipse Doesn't generate Eclispe folder

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Gradle#2]
I've got someone who tried to do "gradlew setupDecompWorkspace eclipse", but had no eclipse folder generated (command typed in NOVA-Wrapper-MC). However, when he typed "gradlew setupDecompWorkspace idea", it generates the .ipr files AND the eclipse folder, which is weird. Shouldn't the eclipse setup also generated the "eclipse" folder?

**Comment by RX14** [comment]
@calclavia It will probably be generated in the subprojects

**Comment by calclavia** [comment]
Ok. What if this mod has no subprojects. Like, we simply want to do gradlew decompWorkspace eclipse without NOVAWrapper being there (NOVA-Wrapper is downloaded as a jar). It's a mod development setup.

**Comment by RX14** [comment]
wait are you trying to use NovaGradle?

**Comment by calclavia** [comment]
No. I wasn't. I'm doing this the nasty way (just create a Forge Gradle file, then add in the NOVA deps etc.)

**Comment by RX14** [comment]
No idea...
