### ISSUE TITLE
Could not resolve nova.gradle:NovaGradle:0.1.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by calclavia** [NOVA-Team/NOVA-Gradle#3]
Tried using your new build script, but it can't find the NOVA Gradle dependency.

Also, how did you add custom wrappers to compile?

**Comment by shadowfacts** [comment]
~~jCenter/NOVA-Gradle needs to be added to the buildscript dependencies. Would do this now but I have to get some sleep.~~

Never mind.

**Comment by calclavia** [comment]
I do have it in dependencies.

``` java
buildscript {
    repositories {
        mavenLocal()
        jcenter()
    }
    dependencies {
        classpath "nova.gradle:NovaGradle:0.1.0-SNAPSHOT"
    }
}
```

**Comment by RX14** [comment]
Calclavia was a derp
